### ISSUE TITLE
css style issue

### ISSUE THREAD

**Issue by archonwang** [dmp1ce/redmine-contracts-with-time-tracking-plugin#62]
@FireMartZ , 
I have met  interesting issue about style with parent issue and subtask. 
I have checked  the html code and found the` child` in source code like this

`<tr id="issue-2734" class="hascontextmenu odd issue tracker-5 status-2 priority-4 priority-high2 overdue child created-by-me assigned-to-me">`

if I remove the  `overdue  child `  it will display ok..... or it will be very messy like the following image
![image](https://cloud.githubusercontent.com/assets/834512/25215924/c96311d6-25d2-11e7-850c-7cce999de150.png)

**Comment by archonwang** [comment]
the code is here

```
<tr id="issue-5" class="hascontextmenu even issue tracker-3 status-1 priority-4 priority-high2 overdue child">
  </tr>
```

the correct code is 

```
<tr id="issue-5" class="hascontextmenu even issue tracker-3 status-1 priority-4 priority-high2">
  </tr>
```

**Comment by FireMartZ** [comment]
@archonwang Thanks for pointing this out.  I changed css to use less common tags in e4b9aa78616468904751bf9cb9f7d184cad88870

**Comment by archonwang** [comment]
@FireMartZ , you're welcome and I will test it tomorrow. Thanks.

**Comment by archonwang** [comment]
@FireMartZ , 
the issue has been fixed and I will close this issue. 
Thanks.

**Comment by archonwang** [comment]
@FireMartZ , 
the issue has been fixed and I will close this issue. 
Thanks.
