### ISSUE TITLE
Error when no Contract present

### ISSUE THREAD

**Issue by alanp5** [dmp1ce/redmine-contracts-with-time-tracking-plugin#65]
For some projects, there isn't necessarily a contract for it. It seems with this install, you can't log any time without a contract being present. If you do you get the following error:

NoMethodError (undefined method `id' for nil:NilClass):
  plugins/contracts/lib/contracts/patches/time_entry_patch.rb:29:in `time_not_exceed_contract'
  app/controllers/timelog_controller.rb:108:in `create'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by alanp5** [comment]
I just noticed that this is already logged as an issue so closing.

**Comment by wesley-jones** [comment]
Thanks @alanp5 for logging your issue. I'm going to try and address this particular issue within the next 2 weeks.
